# Site settings
title: Welcome to Gordon's Blog
header-img: img/home-bg.png
email: gordonsdev@gmail.com
copyright_name: GordonNY
description: > # this means to ignore newlines until "baseurl:"
  Programming Languages Are The Greatest Inventions As Human Languages.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  GordonNY
learn_profile: GordonNY
email_username: gordonsdev@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
